version: '3.8'

services:
  postgres-test:
    image: postgres:13.3
    container_name: postgres-test
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5431:5432"

  redis-test:
    image: redis:latest
    container_name: redis-test
    restart: always
    ports:
      - "6378:6379"

  backend-test:
    build: .
    pull_policy: build
    container_name: backend-test
    restart: always
    depends_on:
      - postgres-test
      - redis-test
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.31.103:5431/test_db
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_REDIS_HOST: 192.168.31.103
      SPRING_REDIS_PORT: 6378
    ports:
      - "8091:8091"

  users-test:
    build: C:\Users\Peregruzochka\Documents\GitHub\telegram_bot
    pull_policy: build
    container_name: tg-bot-user-test
    restart: always
    depends_on:
      - backend-test
      - redis-test
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_REDIS_HOST: 192.168.31.103
      SPRING_REDIS_PORT: 6378
    ports:
      - "8090:8090"

  admin-test:
    build: C:\Users\Peregruzochka\Documents\GitHub\tg_bot_admin
    pull_policy: build
    container_name: tg-bot-admin-test
    restart: always
    depends_on:
      - backend-test
      - redis-test
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_REDIS_HOST: 192.168.31.103
      SPRING_REDIS_PORT: 6378
    ports:
      - "8092:8092"

