spring:
  application:
    name: telegram_bot_backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  data:
    redis-channel:
      new-registration: create-registration
      not-confirmed: not-confirmed

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.springframework: INFO
    ru.peregruzochka.task_management_system: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"

server:
  port: 8081

scheduler:
  get-non-confirmed: 0 */5 * * * *


